disable yellow lab tools

diff --git a/.github/workflows/regression-test-docker-image.yml b/.github/workflows/regression-test-docker-image.yml
--- a/.github/workflows/regression-test-docker-image.yml
+++ b/.github/workflows/regression-test-docker-image.yml
@@ -123,14 +123,14 @@ jobs:
           echo "Error: WebPerf-core testresult is NOT returning expected review"
           exit 1
         fi
-    - name: Check if webperf_core can run Test 17
-      run: |
-        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 17 -r -i sites.json)
-        echo "$testresult"
-        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
-          echo "Error: WebPerf-core testresult is NOT returning expected review"
-          exit 1
-        fi
+    # - name: Check if webperf_core can run Test 17
+    #   run: |
+    #     testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 17 -r -i sites.json)
+    #     echo "$testresult"
+    #     if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+    #       echo "Error: WebPerf-core testresult is NOT returning expected review"
+    #       exit 1
+    #     fi
     - name: Check if webperf_core can run Test 18
       run: |
         testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 18 -r -i sites.json)
