lets check all tests

diff --git a/.github/workflows/regression-test-docker-image.yml b/.github/workflows/regression-test-docker-image.yml
--- a/.github/workflows/regression-test-docker-image.yml
+++ b/.github/workflows/regression-test-docker-image.yml
@@ -51,7 +51,55 @@ jobs:
           echo "Error: WebPerf-core help command is NOT returning expected content"
           exit 1
         fi
-    - name: Check if webperf_core can run Standard files Test
+    - name: Check if webperf_core can run Test 1
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 1 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Performance:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 2
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 2 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Standards:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 4
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 4 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Standards:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 5
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 5 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 6
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 6 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Standards:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 7
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 7 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Standards:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 9
       run: |
         testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 9 -r -i sites.json)
         echo "$testresult"
@@ -59,3 +107,92 @@ jobs:
           echo "Error: WebPerf-core testresult is NOT returning expected review"
           exit 1
         fi
+    - name: Check if webperf_core can run Test 10
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 10 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"A11y:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 15
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 15 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Performance:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 17
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 17 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 18
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 18 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"A11y:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 20
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 20 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+   - name: Check if webperf_core can run Test 21
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 21 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 22
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 22 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Overall:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 23
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 23 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 24
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 24 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 25
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 25 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+    - name: Check if webperf_core can run Test 26
+      run: |
+        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 26 -r -i sites.json)
+        echo "$testresult"
+        if [[ "$testresult" != *"A11y:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
+
