List sitespeed plugins

diff --git a/.github/workflows/regression-test-sitespeed-browsertime-har.yml b/.github/workflows/regression-test-sitespeed-browsertime-har.yml
--- a/.github/workflows/regression-test-sitespeed-browsertime-har.yml
+++ b/.github/workflows/regression-test-sitespeed-browsertime-har.yml
@@ -112,3 +112,34 @@ jobs:
           echo "Error: No path found starting with /sitespeed.io/"
           exit 1
         fi
+    - name: Testing sitespeed.io:s list of plugins using ${{ matrix.browser }}
+      if: always()
+      run: |
+        sitespeedversion=$(python .github/workflows/verify_result.py --docker-sitespeed-version)
+        command="docker run -v $(pwd):/sitespeed.io $sitespeedversion -b ${{ matrix.browser }} -n 1 --plugins.list https://webperf.se"
+        echo "A: $command"
+        testresult=$($command)
+        echo "B: $testresult"
+        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
+        echo "C: $path"
+        if [ -n "$path" ]; then
+          har_file=$(ls -t $(find $(pwd) -name "browsertime.har") | head -1)
+          echo "D: $har_file"
+          if [ -f "$har_file" ]; then
+            echo "Found browsertime.har at $har_file"
+            versions=$(echo "$testresult" | grep -o "VERSIONS:START")
+            echo "E: $versions"
+            if [ -n "$versions" ]; then
+              echo "Versions found in $har_file"
+            else
+              echo "Versions not found in $har_file"
+              exit 1
+            fi
+          else
+            echo "Error: browsertime.har not found in $path"
+            exit 1
+          fi
+        else
+          echo "Error: No path found starting with /sitespeed.io/"
+          exit 1
+        fi
