improved docker regression test

diff --git a/.github/workflows/regression-test-docker-image.yml b/.github/workflows/regression-test-docker-image.yml
--- a/.github/workflows/regression-test-docker-image.yml
+++ b/.github/workflows/regression-test-docker-image.yml
@@ -86,6 +86,10 @@ jobs:
           testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 1 -r -i sites.json)
           echo "$testresult"
         fi
+        if [[ "$testresult" == *"Runtime error encountered"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
         if [[ "$testresult" != *"Performance:"* ]]; then
           echo "Error: WebPerf-core testresult is NOT returning expected review"
           exit 1
@@ -114,6 +118,10 @@ jobs:
           testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 4 -r -i sites.json)
           echo "$testresult"
         fi
+        if [[ "$testresult" == *"Runtime error encountered"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
         if [[ "$testresult" != *"Standards:"* ]]; then
           echo "Error: WebPerf-core testresult is NOT returning expected review"
           exit 1
@@ -132,6 +140,10 @@ jobs:
           sleep 5
           testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 5 -r -i sites.json)
           echo "$testresult"
+        fi
+        if [[ "$testresult" == *"Runtime error encountered"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
         fi
         if [[ "$testresult" != *"Integrity & Security:"* ]]; then
           echo "Error: WebPerf-core testresult is NOT returning expected review"
@@ -178,6 +190,10 @@ jobs:
           sleep 5
           testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 10 -r -i sites.json)
           echo "$testresult"
+        fi
+        if [[ "$testresult" == *"Runtime error encountered"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
         fi
         if [[ "$testresult" != *"A11y:"* ]]; then
           echo "Error: WebPerf-core testresult is NOT returning expected review"
@@ -242,6 +258,10 @@ jobs:
           sleep 5
           testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t 22 -r -i sites.json)
           echo "$testresult"
+        fi
+        if [[ "$testresult" == *"Runtime error encountered"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
         fi
         if [[ "$testresult" != *"Overall:"* ]]; then
           echo "Error: WebPerf-core testresult is NOT returning expected review"
