rabbit.9

diff --git a/.github/workflows/regression-test-docker-image.yml b/.github/workflows/regression-test-docker-image.yml
--- a/.github/workflows/regression-test-docker-image.yml
+++ b/.github/workflows/regression-test-docker-image.yml
@@ -23,10 +23,28 @@ jobs:
     - name: Build the Docker image
       run: docker build -t "webperf-core:latest" .
     - name: Check if we have correct python version
-      run: docker run -v "$(pwd):/webperf-core" webperf-core:latest python --version
+      run: |
+        version=$(docker run -v "$(pwd):/webperf-core" webperf-core:latest python --version)
+        echo "Python version: $version"
+        if [[ "$version" != "Python 3.12"* ]]; then
+          echo "Error: Default python version is not 3.12 based, was we unable to change default version?"
+          exit 1
+        fi
     - name: Check if webperf_core help command works
-      run: docker run -v "$(pwd):/webperf-core" webperf-core:latest python default.py -h
+      run: |
+        help=$(docker run -v "$(pwd):/webperf-core" webperf-core:latest python default.py -h)
+        echo "WebPerf-core Help:\r\n$help"
+        if [[ "$help" != *"-u/--url"* ]]; then
+          echo "Error: WebPerf-core help command is NOT returning expected content"
+          exit 1
+        fi
     - name: Check if webperf_core can run Standard files Test
-      run: docker run -v "$(pwd):/webperf-core" webperf-core:latest python default.py -t ${{ matrix.version }} -r -i sites.json -o .github/workflows/testresult-${{ matrix.version }}.json
+      run: |
+        testresult=$(docker run -v "$(pwd):/webperf-core" webperf-core:latest python default.py -t ${{ matrix.version }} -r -i sites.json -o .github/workflows/testresult-${{ matrix.version }}.json)
+        echo "WebPerf-core testresult:\r\n$testresult"
+        if [[ "$testresult" != *"Integrity & Security:"* ]]; then
+          echo "Error: WebPerf-core testresult is NOT returning expected review"
+          exit 1
+        fi
     - name: Check if webperf_core returned correct data output in Standard files Regression Test
       run: docker run -v "$(pwd):/webperf-core" webperf-core:latest python .github/workflows/verify_result.py -t ${{ matrix.version }}
